from thermometer import Thermometer
term= Thermometer()
term.turn_on()
term.measurement()
term.display()
term.turn_off()
print()
print()
print()
print()
term.turn_on()
term.display()
term.turn_off()
term.measurement()